// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxtugumpkvfagxwnjqsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dHVndW1wa3ZmYWd4d25qcXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MjAyNzgsImV4cCI6MjA5MjI5NjI3OH0.Q39bLjqZDkB8juY-1fBcw9Wy2N1BylkHq-ghpHqBbBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});